import { Article, Category, Author } from '@/types';

export const mockAuthors: Author[] = [
  {
    id: '1',
    email: 'sarah@example.com',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    bio: 'Technology journalist and AI researcher',
    role: 'admin',
  },
  {
    id: '2',
    email: 'marcus@example.com',
    name: 'Marcus Johnson',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    bio: 'Senior editor covering digital culture',
    role: 'editor',
  },
  {
    id: '3',
    email: 'aisha@example.com',
    name: 'Aisha Rahman',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    bio: 'Design and creativity correspondent',
    role: 'editor',
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    slug: 'technology',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
    translations: [
      { id: '1-en', categoryId: '1', locale: 'en', name: 'Technology', description: 'Latest in tech and innovation' },
      { id: '1-ar', categoryId: '1', locale: 'ar', name: 'التكنولوجيا', description: 'أحدث التقنيات والابتكارات' },
    ],
  },
  {
    id: '2',
    slug: 'design',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
    translations: [
      { id: '2-en', categoryId: '2', locale: 'en', name: 'Design', description: 'Design trends and inspiration' },
      { id: '2-ar', categoryId: '2', locale: 'ar', name: 'التصميم', description: 'اتجاهات التصميم والإلهام' },
    ],
  },
  {
    id: '3',
    slug: 'culture',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
    translations: [
      { id: '3-en', categoryId: '3', locale: 'en', name: 'Culture', description: 'Exploring modern culture' },
      { id: '3-ar', categoryId: '3', locale: 'ar', name: 'الثقافة', description: 'استكشاف الثقافة الحديثة' },
    ],
  },
  {
    id: '4',
    slug: 'business',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
    translations: [
      { id: '4-en', categoryId: '4', locale: 'en', name: 'Business', description: 'Business insights and analysis' },
      { id: '4-ar', categoryId: '4', locale: 'ar', name: 'الأعمال', description: 'رؤى وتحليلات الأعمال' },
    ],
  },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    slug: 'the-future-of-artificial-intelligence',
    featuredImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=800&fit=crop',
    categoryId: '1',
    category: mockCategories[0],
    authorId: '1',
    author: mockAuthors[0],
    status: 'published',
    publishedAt: '2024-12-20',
    createdAt: '2024-12-18',
    updatedAt: '2024-12-20',
    translations: [
      {
        id: '1-en',
        articleId: '1',
        locale: 'en',
        title: 'The Future of Artificial Intelligence: A Deep Dive into What\'s Next',
        excerpt: 'Exploring the transformative potential of AI and its impact on society, from healthcare to creative industries.',
        content: `<h2>Introduction</h2><p>Artificial Intelligence has evolved from a science fiction concept to an integral part of our daily lives. From the recommendations we see on streaming platforms to the voice assistants in our homes, AI is reshaping how we interact with technology.</p><h2>The Current State of AI</h2><p>Today's AI systems are more capable than ever before. Large language models can engage in nuanced conversations, generate creative content, and assist with complex problem-solving. Computer vision systems can identify objects with superhuman accuracy, and reinforcement learning algorithms are mastering tasks that once seemed impossible.</p><h2>What's Next?</h2><p>The next frontier of AI development promises even more remarkable advances. We're seeing the emergence of multimodal systems that can seamlessly process text, images, audio, and video. These systems are becoming more efficient, more accessible, and more integrated into our daily workflows.</p><blockquote>The question is no longer whether AI will transform our world, but how we can ensure that transformation benefits everyone.</blockquote><p>As we look to the future, the ethical considerations surrounding AI become increasingly important. How do we ensure fairness in AI systems? How do we maintain privacy while leveraging data? These are the questions that will shape the next chapter of AI development.</p>`,
        metaTitle: 'The Future of AI: What\'s Next for Artificial Intelligence | Editorial',
        metaDescription: 'Discover the transformative potential of AI and its impact on society. Explore the latest developments in artificial intelligence and what they mean for our future.',
        readingTime: 8,
      },
      {
        id: '1-ar',
        articleId: '1',
        locale: 'ar',
        title: 'مستقبل الذكاء الاصطناعي: نظرة عميقة على ما هو قادم',
        excerpt: 'استكشاف الإمكانات التحويلية للذكاء الاصطناعي وتأثيره على المجتمع، من الرعاية الصحية إلى الصناعات الإبداعية.',
        content: `<h2>مقدمة</h2><p>تطور الذكاء الاصطناعي من مفهوم الخيال العلمي إلى جزء لا يتجزأ من حياتنا اليومية. من التوصيات التي نراها على منصات البث إلى المساعدين الصوتيين في منازلنا، يعيد الذكاء الاصطناعي تشكيل طريقة تفاعلنا مع التكنولوجيا.</p><h2>الوضع الحالي للذكاء الاصطناعي</h2><p>أنظمة الذكاء الاصطناعي اليوم أكثر قدرة من أي وقت مضى. يمكن لنماذج اللغة الكبيرة المشاركة في محادثات دقيقة وتوليد محتوى إبداعي والمساعدة في حل المشكلات المعقدة.</p>`,
        metaTitle: 'مستقبل الذكاء الاصطناعي | التحريري',
        metaDescription: 'اكتشف الإمكانات التحويلية للذكاء الاصطناعي وتأثيره على المجتمع.',
        readingTime: 8,
      },
    ],
  },
  {
    id: '2',
    slug: 'minimalist-design-principles',
    featuredImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&h=800&fit=crop',
    categoryId: '2',
    category: mockCategories[1],
    authorId: '3',
    author: mockAuthors[2],
    status: 'published',
    publishedAt: '2024-12-19',
    createdAt: '2024-12-17',
    updatedAt: '2024-12-19',
    translations: [
      {
        id: '2-en',
        articleId: '2',
        locale: 'en',
        title: 'Minimalist Design Principles for the Modern Web',
        excerpt: 'How less truly becomes more in contemporary digital design. A guide to creating elegant, user-focused experiences.',
        content: `<h2>The Power of Simplicity</h2><p>In a world of constant digital noise, minimalist design offers a breath of fresh air. By stripping away the unnecessary, we allow what matters most to shine through.</p><h2>Key Principles</h2><p>Effective minimalist design isn't about removing everything—it's about being intentional with every element that remains. Typography, whitespace, and subtle interactions become the building blocks of a refined experience.</p>`,
        metaTitle: 'Minimalist Design Principles for Modern Web | Editorial',
        metaDescription: 'Learn how to create elegant, user-focused web experiences through minimalist design principles.',
        readingTime: 6,
      },
      {
        id: '2-ar',
        articleId: '2',
        locale: 'ar',
        title: 'مبادئ التصميم البسيط للويب الحديث',
        excerpt: 'كيف يصبح الأقل حقاً هو الأكثر في التصميم الرقمي المعاصر. دليل لإنشاء تجارب أنيقة تركز على المستخدم.',
        content: `<h2>قوة البساطة</h2><p>في عالم من الضوضاء الرقمية المستمرة، يقدم التصميم البسيط نفساً من الهواء النقي. من خلال إزالة ما هو غير ضروري، نسمح لما هو أكثر أهمية بالتألق.</p>`,
        metaTitle: 'مبادئ التصميم البسيط | التحريري',
        metaDescription: 'تعلم كيفية إنشاء تجارب ويب أنيقة تركز على المستخدم من خلال مبادئ التصميم البسيط.',
        readingTime: 6,
      },
    ],
  },
  {
    id: '3',
    slug: 'digital-nomad-culture',
    featuredImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&h=800&fit=crop',
    categoryId: '3',
    category: mockCategories[2],
    authorId: '2',
    author: mockAuthors[1],
    status: 'published',
    publishedAt: '2024-12-18',
    createdAt: '2024-12-16',
    updatedAt: '2024-12-18',
    translations: [
      {
        id: '3-en',
        articleId: '3',
        locale: 'en',
        title: 'The Rise of Digital Nomad Culture: Working Without Borders',
        excerpt: 'How remote work is reshaping our relationship with place, community, and professional identity.',
        content: `<h2>A New Way of Working</h2><p>The pandemic accelerated a trend that was already underway: the decoupling of work from physical location. Today, millions of professionals are embracing the digital nomad lifestyle.</p><h2>Beyond the Instagram Dream</h2><p>While the reality of digital nomadism includes genuine benefits—flexibility, cultural exposure, adventure—it also comes with challenges that are rarely discussed in glossy social media posts.</p>`,
        metaTitle: 'Digital Nomad Culture: Working Without Borders | Editorial',
        metaDescription: 'Explore how remote work is reshaping our relationship with place, community, and professional identity.',
        readingTime: 7,
      },
      {
        id: '3-ar',
        articleId: '3',
        locale: 'ar',
        title: 'صعود ثقافة الرحالة الرقميين: العمل بدون حدود',
        excerpt: 'كيف يعيد العمل عن بعد تشكيل علاقتنا بالمكان والمجتمع والهوية المهنية.',
        content: `<h2>طريقة جديدة للعمل</h2><p>سرّعت الجائحة اتجاهاً كان جارياً بالفعل: فصل العمل عن الموقع الجغرافي. اليوم، يتبنى الملايين من المحترفين نمط حياة الرحالة الرقمي.</p>`,
        metaTitle: 'ثقافة الرحالة الرقميين | التحريري',
        metaDescription: 'استكشف كيف يعيد العمل عن بعد تشكيل علاقتنا بالمكان والمجتمع والهوية المهنية.',
        readingTime: 7,
      },
    ],
  },
  {
    id: '4',
    slug: 'startup-ecosystem-2024',
    featuredImage: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1200&h=800&fit=crop',
    categoryId: '4',
    category: mockCategories[3],
    authorId: '1',
    author: mockAuthors[0],
    status: 'published',
    publishedAt: '2024-12-17',
    createdAt: '2024-12-15',
    updatedAt: '2024-12-17',
    translations: [
      {
        id: '4-en',
        articleId: '4',
        locale: 'en',
        title: 'The Startup Ecosystem in 2024: Trends and Predictions',
        excerpt: 'What founders need to know about funding, growth, and sustainability in today\'s competitive landscape.',
        content: `<h2>The Funding Landscape</h2><p>After the exuberance of 2021 and the correction of 2022-2023, the startup funding environment has reached a new equilibrium. Investors are more selective, but quality companies continue to attract capital.</p><h2>Key Trends</h2><p>AI remains the dominant theme, but we're seeing maturation in how startups approach the technology. The focus has shifted from novelty to utility—from "we use AI" to "here's the specific problem we solve."</p>`,
        metaTitle: 'Startup Ecosystem 2024: Trends and Predictions | Editorial',
        metaDescription: 'Discover what founders need to know about funding, growth, and sustainability in today\'s startup landscape.',
        readingTime: 9,
      },
      {
        id: '4-ar',
        articleId: '4',
        locale: 'ar',
        title: 'النظام البيئي للشركات الناشئة في 2024: الاتجاهات والتوقعات',
        excerpt: 'ما يحتاج المؤسسون معرفته حول التمويل والنمو والاستدامة في المشهد التنافسي اليوم.',
        content: `<h2>مشهد التمويل</h2><p>بعد الحماس المفرط في 2021 والتصحيح في 2022-2023، وصلت بيئة تمويل الشركات الناشئة إلى توازن جديد. أصبح المستثمرون أكثر انتقائية، لكن الشركات عالية الجودة تستمر في جذب رأس المال.</p>`,
        metaTitle: 'النظام البيئي للشركات الناشئة 2024 | التحريري',
        metaDescription: 'اكتشف ما يحتاج المؤسسون معرفته حول التمويل والنمو والاستدامة.',
        readingTime: 9,
      },
    ],
  },
  {
    id: '5',
    slug: 'sustainable-technology',
    featuredImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=800&fit=crop',
    categoryId: '1',
    category: mockCategories[0],
    authorId: '2',
    author: mockAuthors[1],
    status: 'published',
    publishedAt: '2024-12-16',
    createdAt: '2024-12-14',
    updatedAt: '2024-12-16',
    translations: [
      {
        id: '5-en',
        articleId: '5',
        locale: 'en',
        title: 'Sustainable Technology: Building a Greener Digital Future',
        excerpt: 'How the tech industry is addressing its environmental impact and pioneering sustainable solutions.',
        content: `<h2>The Environmental Cost of Digital</h2><p>Every email, every search query, every video stream has a carbon footprint. As our digital lives expand, so does the environmental impact of the infrastructure that powers them.</p><h2>Innovative Solutions</h2><p>From carbon-neutral data centers to more efficient algorithms, the tech industry is developing creative approaches to sustainability.</p>`,
        metaTitle: 'Sustainable Technology: Building a Greener Digital Future | Editorial',
        metaDescription: 'Explore how the tech industry is addressing its environmental impact and pioneering sustainable solutions.',
        readingTime: 5,
      },
      {
        id: '5-ar',
        articleId: '5',
        locale: 'ar',
        title: 'التكنولوجيا المستدامة: بناء مستقبل رقمي أكثر اخضراراً',
        excerpt: 'كيف تتعامل صناعة التكنولوجيا مع تأثيرها البيئي وتقود الحلول المستدامة.',
        content: `<h2>التكلفة البيئية للرقمنة</h2><p>لكل بريد إلكتروني، لكل استعلام بحث، لكل بث فيديو بصمة كربونية. مع توسع حياتنا الرقمية، يتوسع أيضاً التأثير البيئي للبنية التحتية التي تشغلها.</p>`,
        metaTitle: 'التكنولوجيا المستدامة | التحريري',
        metaDescription: 'استكشف كيف تتعامل صناعة التكنولوجيا مع تأثيرها البيئي.',
        readingTime: 5,
      },
    ],
  },
];

// Helper functions
export function getArticleTranslation(article: Article, locale: 'en' | 'ar') {
  return article.translations.find(t => t.locale === locale) || article.translations[0];
}

export function getCategoryTranslation(category: Category, locale: 'en' | 'ar') {
  return category.translations.find(t => t.locale === locale) || category.translations[0];
}
